from __future__ import annotations


DAILY_HOURLY_ALGORITHM_ID = "BAZI-DAILY-HOURLY-FLOW-SIDECAR-R1"
DAILY_HOURLY_ALGORITHM_VERSION = "1.0.0"
DAILY_RULE_SET_ID = "BAZI-DAILY-FRAME-R1"
DAILY_RULE_SET_VERSION = "1.0.0"
HOURLY_RULE_SET_ID = "BAZI-HOURLY-FRAME-R1"
HOURLY_RULE_SET_VERSION = "1.0.0"
INTERVAL_SEMANTICS = "START_INCLUSIVE_END_EXCLUSIVE"
