"""Project-owned operational dependency/minor Dignity registry data for R3.

Generated from the closed 21-export external compatibility calibration set.
External software is provenance only and is not canonical source authority.
This module contains data only; typing/validation lives in dignity.py.
"""

OPERATIONAL_DEPENDENCY_MINOR_DIGNITY_RAW_BY_BRANCH: dict[str, dict[str, tuple[str, str | None]]] = {
    "STAR.SANTAI": {
        "子": ("GRADED", '平'),
        "丑": ("GRADED", '庙'),
        "寅": ("GRADED", '平'),
        "卯": ("GRADED", '陷'),
        "辰": ("GRADED", '庙'),
        "巳": ("GRADED", '平'),
        "午": ("GRADED", '旺'),
        "未": ("GRADED", '庙'),
        "申": ("GRADED", '旺'),
        "酉": ("GRADED", '庙'),
        "戌": ("GRADED", '旺'),
        "亥": ("GRADED", '平'),
    },
    "STAR.BAZUO": {
        "子": ("GRADED", '陷'),
        "丑": ("GRADED", '庙'),
        "寅": ("GRADED", '庙'),
        "卯": ("GRADED", '平'),
        "辰": ("GRADED", '旺'),
        "巳": ("GRADED", '庙'),
        "午": ("GRADED", '庙'),
        "未": ("GRADED", '平'),
        "申": ("GRADED", '平'),
        "酉": ("GRADED", '庙'),
        "戌": ("GRADED", '平'),
        "亥": ("GRADED", '庙'),
    },
    "STAR.ENGUANG": {
        "子": ("GRADED", '平'),
        "丑": ("GRADED", '庙'),
        "寅": ("GRADED", '庙'),
        "卯": ("GRADED", '庙'),
        "辰": ("GRADED", '庙'),
        "巳": ("GRADED", '平'),
        "午": ("GRADED", '庙'),
        "未": ("GRADED", '庙'),
        "申": ("GRADED", '平'),
        "酉": ("GRADED", '庙'),
        "戌": ("GRADED", '庙'),
        "亥": ("GRADED", '不'),
    },
    "STAR.TIANGUI": {
        "子": ("GRADED", '旺'),
        "丑": ("GRADED", '庙'),
        "寅": ("GRADED", '庙'),
        "卯": ("GRADED", '旺'),
        "辰": ("GRADED", '旺'),
        "巳": ("GRADED", '庙'),
        "午": ("GRADED", '庙'),
        "未": ("GRADED", '旺'),
        "申": ("GRADED", '旺'),
        "酉": ("GRADED", '庙'),
        "戌": ("GRADED", '旺'),
        "亥": ("GRADED", '庙'),
    },
    "STAR.TIANGUAN": {
        "寅": ("GRADED", '平'),
        "卯": ("GRADED", '庙'),
        "辰": ("GRADED", '旺'),
        "巳": ("GRADED", '庙'),
        "午": ("GRADED", '旺'),
        "未": ("GRADED", '庙'),
        "酉": ("GRADED", '平'),
        "戌": ("GRADED", '平'),
        "亥": ("GRADED", '旺'),
    },
    "STAR.TIANFU_BLESSING": {
        "子": ("GRADED", '庙'),
        "寅": ("GRADED", '庙'),
        "卯": ("GRADED", '旺'),
        "巳": ("GRADED", '旺'),
        "午": ("GRADED", '平'),
        "申": ("GRADED", '庙'),
        "酉": ("GRADED", '庙'),
        "亥": ("GRADED", '旺'),
    },
    "STAR.TIANCHU": {
        "子": ("UNRATED", None),
        "寅": ("UNRATED", None),
        "巳": ("UNRATED", None),
        "午": ("UNRATED", None),
        "申": ("UNRATED", None),
        "酉": ("UNRATED", None),
        "亥": ("UNRATED", None),
    },
    "STAR.JIEKONG": {
        "子": ("GRADED", '庙'),
        "丑": ("GRADED", '不'),
        "寅": ("GRADED", '陷'),
        "卯": ("GRADED", '庙'),
        "辰": ("GRADED", '陷'),
        "巳": ("GRADED", '庙'),
        "午": ("GRADED", '庙'),
        "未": ("GRADED", '庙'),
        "申": ("GRADED", '庙'),
        "酉": ("GRADED", '庙'),
    },
    "STAR.FU_JIEKONG": {
        "子": ("GRADED", '陷'),
        "丑": ("GRADED", '庙'),
        "寅": ("GRADED", '庙'),
        "卯": ("GRADED", '平'),
        "辰": ("GRADED", '陷'),
        "巳": ("GRADED", '庙'),
        "午": ("GRADED", '庙'),
        "未": ("GRADED", '庙'),
        "申": ("GRADED", '庙'),
        "酉": ("GRADED", '庙'),
    },
    "STAR.XUNKONG": {
        "子": ("GRADED", '得'),
        "丑": ("GRADED", '平'),
        "寅": ("GRADED", '陷'),
        "卯": ("GRADED", '平'),
        "辰": ("GRADED", '陷'),
        "巳": ("GRADED", '庙'),
        "午": ("GRADED", '庙'),
        "未": ("GRADED", '庙'),
        "申": ("GRADED", '庙'),
        "酉": ("GRADED", '庙'),
        "戌": ("GRADED", '陷'),
        "亥": ("GRADED", '平'),
    },
    "STAR.FU_XUNKONG": {
        "子": ("GRADED", '陷'),
        "丑": ("GRADED", '庙'),
        "寅": ("GRADED", '陷'),
        "卯": ("GRADED", '平'),
        "辰": ("GRADED", '陷'),
        "巳": ("GRADED", '庙'),
        "午": ("GRADED", '庙'),
        "未": ("GRADED", '庙'),
        "申": ("GRADED", '庙'),
        "酉": ("GRADED", '庙'),
        "戌": ("GRADED", '陷'),
        "亥": ("GRADED", '平'),
    },
    "STAR.TIANKONG": {
        "子": ("GRADED", '陷'),
        "丑": ("GRADED", '平'),
        "寅": ("GRADED", '陷'),
        "卯": ("GRADED", '旺'),
        "辰": ("GRADED", '庙'),
        "巳": ("GRADED", '庙'),
        "午": ("GRADED", '庙'),
        "未": ("GRADED", '庙'),
        "申": ("GRADED", '旺'),
        "酉": ("GRADED", '旺'),
        "戌": ("GRADED", '陷'),
        "亥": ("GRADED", '平'),
    },
    "STAR.TIANKU": {
        "子": ("GRADED", '平'),
        "丑": ("GRADED", '庙'),
        "寅": ("GRADED", '陷'),
        "卯": ("GRADED", '庙'),
        "辰": ("GRADED", '庙'),
        "巳": ("GRADED", '平'),
        "午": ("GRADED", '陷'),
        "未": ("GRADED", '平'),
        "申": ("GRADED", '庙'),
        "酉": ("GRADED", '庙'),
        "戌": ("GRADED", '平'),
        "亥": ("GRADED", '平'),
    },
    "STAR.TIANXU": {
        "子": ("GRADED", '陷'),
        "丑": ("GRADED", '庙'),
        "寅": ("GRADED", '旺'),
        "卯": ("GRADED", '庙'),
        "辰": ("GRADED", '陷'),
        "巳": ("GRADED", '旺'),
        "午": ("GRADED", '平'),
        "未": ("GRADED", '陷'),
        "申": ("GRADED", '旺'),
        "酉": ("GRADED", '旺'),
        "戌": ("GRADED", '陷'),
        "亥": ("GRADED", '平'),
    },
    "STAR.HONGLUAN": {
        "子": ("GRADED", '庙'),
        "丑": ("GRADED", '旺'),
        "寅": ("GRADED", '旺'),
        "卯": ("GRADED", '庙'),
        "辰": ("GRADED", '庙'),
        "巳": ("GRADED", '旺'),
        "午": ("GRADED", '陷'),
        "未": ("GRADED", '陷'),
        "申": ("GRADED", '庙'),
        "酉": ("GRADED", '旺'),
        "戌": ("GRADED", '陷'),
        "亥": ("GRADED", '旺'),
    },
    "STAR.TIANXI": {
        "子": ("GRADED", '旺'),
        "丑": ("GRADED", '陷'),
        "寅": ("GRADED", '庙'),
        "卯": ("GRADED", '庙'),
        "辰": ("GRADED", '旺'),
        "巳": ("GRADED", '陷'),
        "午": ("GRADED", '庙'),
        "未": ("GRADED", '旺'),
        "申": ("GRADED", '旺'),
        "酉": ("GRADED", '庙'),
        "戌": ("GRADED", '陷'),
        "亥": ("GRADED", '旺'),
    },
    "STAR.GUCHEN": {
        "寅": ("GRADED", '平'),
        "巳": ("GRADED", '陷'),
        "申": ("GRADED", '平'),
        "亥": ("GRADED", '陷'),
    },
    "STAR.GUASU": {
        "丑": ("GRADED", '平'),
        "辰": ("GRADED", '陷'),
        "未": ("GRADED", '不'),
        "戌": ("GRADED", '陷'),
    },
    "STAR.JIESHA": {
        "寅": ("UNRATED", None),
        "巳": ("UNRATED", None),
        "申": ("UNRATED", None),
        "亥": ("UNRATED", None),
    },
    "STAR.DAHAO": {
        "子": ("GRADED", '旺'),
        "丑": ("GRADED", '平'),
        "寅": ("GRADED", '陷'),
        "卯": ("GRADED", '不'),
        "辰": ("GRADED", '平'),
        "巳": ("GRADED", '陷'),
        "午": ("GRADED", '旺'),
        "未": ("GRADED", '平'),
        "申": ("GRADED", '陷'),
        "酉": ("GRADED", '不'),
        "戌": ("GRADED", '平'),
        "亥": ("GRADED", '陷'),
    },
    "STAR.FEILIAN": {
        "子": ("UNRATED", None),
        "丑": ("UNRATED", None),
        "寅": ("UNRATED", None),
        "卯": ("UNRATED", None),
        "辰": ("UNRATED", None),
        "巳": ("UNRATED", None),
        "午": ("UNRATED", None),
        "未": ("UNRATED", None),
        "申": ("UNRATED", None),
        "酉": ("UNRATED", None),
        "戌": ("UNRATED", None),
        "亥": ("UNRATED", None),
    },
    "STAR.POSUI": {
        "丑": ("GRADED", '陷'),
        "巳": ("GRADED", '陷'),
        "酉": ("GRADED", '平'),
    },
    "STAR.HUAGAI": {
        "丑": ("GRADED", '陷'),
        "辰": ("GRADED", '庙'),
        "未": ("GRADED", '陷'),
        "戌": ("GRADED", '平'),
    },
    "STAR.XIANCHI": {
        "子": ("GRADED", '陷'),
        "卯": ("GRADED", '平'),
        "午": ("GRADED", '陷'),
        "酉": ("GRADED", '平'),
    },
    "STAR.LONGDE": {
        "子": ("UNRATED", None),
        "丑": ("UNRATED", None),
        "寅": ("UNRATED", None),
        "卯": ("UNRATED", None),
        "辰": ("UNRATED", None),
        "巳": ("UNRATED", None),
        "午": ("UNRATED", None),
        "未": ("UNRATED", None),
        "申": ("UNRATED", None),
        "酉": ("UNRATED", None),
        "戌": ("UNRATED", None),
        "亥": ("UNRATED", None),
    },
    "STAR.YUEDE": {
        "子": ("UNRATED", None),
        "丑": ("UNRATED", None),
        "寅": ("UNRATED", None),
        "卯": ("UNRATED", None),
        "辰": ("UNRATED", None),
        "巳": ("UNRATED", None),
        "午": ("UNRATED", None),
        "未": ("UNRATED", None),
        "申": ("UNRATED", None),
        "酉": ("UNRATED", None),
        "戌": ("UNRATED", None),
        "亥": ("UNRATED", None),
    },
    "STAR.TIANDE": {
        "子": ("GRADED", '庙'),
        "丑": ("GRADED", '旺'),
        "寅": ("GRADED", '平'),
        "卯": ("GRADED", '庙'),
        "辰": ("GRADED", '庙'),
        "巳": ("GRADED", '旺'),
        "午": ("GRADED", '庙'),
        "未": ("GRADED", '庙'),
        "申": ("GRADED", '平'),
        "酉": ("GRADED", '不'),
        "戌": ("GRADED", '庙'),
        "亥": ("GRADED", '旺'),
    },
    "STAR.NIANJIE": {
        "子": ("GRADED", '庙'),
        "丑": ("GRADED", '旺'),
        "寅": ("GRADED", '庙'),
        "卯": ("GRADED", '庙'),
        "辰": ("GRADED", '得'),
        "巳": ("GRADED", '旺'),
        "午": ("GRADED", '庙'),
        "未": ("GRADED", '得'),
        "申": ("GRADED", '庙'),
        "酉": ("GRADED", '庙'),
        "戌": ("GRADED", '庙'),
        "亥": ("GRADED", '得'),
    },
    "STAR.TIANCAI": {
        "子": ("GRADED", '旺'),
        "丑": ("GRADED", '平'),
        "寅": ("GRADED", '庙'),
        "卯": ("GRADED", '旺'),
        "辰": ("GRADED", '陷'),
        "巳": ("GRADED", '旺'),
        "午": ("GRADED", '旺'),
        "未": ("GRADED", '平'),
        "申": ("GRADED", '庙'),
        "酉": ("GRADED", '旺'),
        "戌": ("GRADED", '陷'),
        "亥": ("GRADED", '庙'),
    },
    "STAR.LONGCHI": {
        "子": ("GRADED", '旺'),
        "丑": ("GRADED", '平'),
        "寅": ("GRADED", '平'),
        "卯": ("GRADED", '庙'),
        "辰": ("GRADED", '庙'),
        "巳": ("GRADED", '平'),
        "午": ("GRADED", '陷'),
        "未": ("GRADED", '庙'),
        "申": ("GRADED", '旺'),
        "酉": ("GRADED", '庙'),
        "戌": ("GRADED", '平'),
        "亥": ("GRADED", '旺'),
    },
    "STAR.FENGGE": {
        "子": ("GRADED", '庙'),
        "丑": ("GRADED", '平'),
        "寅": ("GRADED", '庙'),
        "卯": ("GRADED", '旺'),
        "辰": ("GRADED", '庙'),
        "巳": ("GRADED", '平'),
        "午": ("GRADED", '陷'),
        "未": ("GRADED", '陷'),
        "申": ("GRADED", '旺'),
        "酉": ("GRADED", '庙'),
        "戌": ("GRADED", '庙'),
        "亥": ("GRADED", '旺'),
    },
    "STAR.TAIFU": {
        "子": ("UNRATED", None),
        "丑": ("UNRATED", None),
        "寅": ("UNRATED", None),
        "卯": ("UNRATED", None),
        "辰": ("UNRATED", None),
        "巳": ("UNRATED", None),
        "午": ("UNRATED", None),
        "未": ("UNRATED", None),
        "申": ("UNRATED", None),
        "酉": ("UNRATED", None),
        "戌": ("UNRATED", None),
        "亥": ("UNRATED", None),
    },
    "STAR.FENGGAO": {
        "子": ("UNRATED", None),
        "丑": ("UNRATED", None),
        "寅": ("UNRATED", None),
        "卯": ("UNRATED", None),
        "辰": ("UNRATED", None),
        "巳": ("UNRATED", None),
        "午": ("UNRATED", None),
        "未": ("UNRATED", None),
        "申": ("UNRATED", None),
        "酉": ("UNRATED", None),
        "戌": ("UNRATED", None),
        "亥": ("UNRATED", None),
    },
    "STAR.TIANXING": {
        "子": ("GRADED", '平'),
        "丑": ("GRADED", '陷'),
        "寅": ("GRADED", '陷'),
        "卯": ("GRADED", '庙'),
        "辰": ("GRADED", '平'),
        "巳": ("GRADED", '平'),
        "午": ("GRADED", '庙'),
        "未": ("GRADED", '陷'),
        "申": ("GRADED", '陷'),
        "酉": ("GRADED", '庙'),
        "戌": ("GRADED", '平'),
        "亥": ("GRADED", '陷'),
    },
    "STAR.TIANYAO": {
        "子": ("GRADED", '庙'),
        "丑": ("GRADED", '平'),
        "寅": ("GRADED", '平'),
        "卯": ("GRADED", '庙'),
        "辰": ("GRADED", '陷'),
        "巳": ("GRADED", '平'),
        "午": ("GRADED", '庙'),
        "未": ("GRADED", '旺'),
        "申": ("GRADED", '陷'),
        "酉": ("GRADED", '庙'),
        "戌": ("GRADED", '陷'),
        "亥": ("GRADED", '陷'),
    },
    "STAR.JIESHEN": {
        "子": ("GRADED", '不'),
        "寅": ("GRADED", '庙'),
        "辰": ("GRADED", '平'),
        "午": ("GRADED", '庙'),
        "申": ("GRADED", '不'),
        "戌": ("GRADED", '庙'),
    },
    "STAR.TIANWU": {
        "寅": ("UNRATED", None),
        "巳": ("UNRATED", None),
        "申": ("UNRATED", None),
        "亥": ("UNRATED", None),
    },
    "STAR.TIANYUE_MOON": {
        "寅": ("UNRATED", None),
        "卯": ("UNRATED", None),
        "辰": ("UNRATED", None),
        "巳": ("UNRATED", None),
        "午": ("UNRATED", None),
        "未": ("UNRATED", None),
        "戌": ("UNRATED", None),
        "亥": ("UNRATED", None),
    },
    "STAR.YINSHA": {
        "子": ("UNRATED", None),
        "寅": ("UNRATED", None),
        "辰": ("UNRATED", None),
        "午": ("UNRATED", None),
        "申": ("UNRATED", None),
        "戌": ("UNRATED", None),
    },
}
